# Generated by Django 5.2.6 on 2025-10-15 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='La note ne peut pas être inférieure à 0.'), django.core.validators.MaxValueValidator(20.0, message='La note ne peut pas être supérieure à 20.')]),
        ),
    ]
