# Generated by Django 5.2.6 on 2025-10-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_unique_together_alter_note_valeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='eleves',
        ),
        migrations.AddField(
            model_name='eleve',
            name='matieres_suivies',
            field=models.ManyToManyField(blank=True, related_name='eleves', to='notes.matiere'),
        ),
    ]
